output_root: "outputs"
output_version: "v0321_allobj"
backup_name: "weights"
log_name: "logs"
model_name: "Yolov2_Meta"
# all labels
labels: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]

# base labels
#labels:  ['aeroplane', 'bicycle', 'boat', 'bottle', 'car', 'cat', 'chair', 'diningtable', 'dog', 'horse', 'person', 'pottedplant', 'sheep', 'train', 'tvmonitor']
data_root_dir: "../VOCdevkit/onedet_cache"

train:
    dataset: "k_shot_3_joint" #"k_shot_base" #"k_shot_joint"
    stdout: False
    gpus: "2,3,0,1"
    nworkers: 16
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: False

    warmup_lr: 0.0001
    lr_steps: [500, 40000, 60000]
    lr_rates: [0.001,0.0001, 0.00001]
    max_batches: 90000
    resize_interval: 10

    backup_interval: 200
    backup_steps: [1000, 60000]
    backup_rates: [1000, 1000]

    input_shape: [416, 416]
    meta_input_shape: [416, 416]
    batch_size: 48
    mini_batch_size: 48
    weights: "weights/darknet19_448.conv.23"

test:
    dataset: 'test' #'k_shot_base_test' # "test
    stdout: True
    gpus: "3"
    nworkers: 16
    pin_mem: True
    input_shape: [416, 416]
    batch_size: 32
    weights: "outputs/Yolov2_Meta/parallel/weights/weights_8000.pt"
    conf_thresh: 0.05
    nms_thresh: 0.45
    reweights: "outputs/Yolov2_Meta/parallel/weights/reweights_8000.pkl"
    results: "re_190320_parallel"

weights:
    dataset: "k_shot_3_joint" #'two_class_base' # "test"
    stdout: True
    gpus: "3"
    nworkers: 4
    pin_mem: True

    input_shape: [416, 416]
    batch_size: 1
    weights: "outputs/Yolov2_Meta/parallel/weights/weights_8000.pt"
    results: "outputs/Yolov2_Meta/parallel/weights/reweights_8000.pkl"
speed:
    gpus: "7"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]
