output_root: "outputs"
output_version: "meta_two_class_great_metanet_lr"
backup_name: "weights"
log_name: "logs"

# all labels
#labels: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]

# base labels
labels: ['train', 'tvmonitor'] # ['aeroplane', 'bicycle', 'boat', 'bottle', 'car', 'cat', 'chair', 'diningtable', 'dog', 'horse', 'person', 'pottedplant', 'sheep', 'train', 'tvmonitor']
data_root_dir: "../VOCdevkit/onedet_cache"

train:
    dataset: 'two_class_base' # "k_shot_base" #"k_shot_joint"
    stdout: True
    gpus: "0"
    nworkers: 16
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: False

    warmup_lr: 0.00001
    lr_steps: [500, 1000, 30000, 35000]
    lr_rates: [0.00005,0.0001, 0.00001,0.000001]
    max_batches: 40000
    resize_interval: 10

    backup_interval: 200
    backup_steps: [1000, 60000]
    backup_rates: [1000, 200]

    input_shape: [608, 608]
    meta_input_shape: [416, 416]
    batch_size: 64
    mini_batch_size: 8
    weights: "weights/darknet19_448.conv.23"

test:
    dataset: 'two_class_base_test' #'k_shot_base_test' # "test"
    stdout: True
    gpus: "2"
    nworkers: 4
    pin_mem: True

    input_shape: [544, 544]
    batch_size: 32
    weights: "outputs/Yolov2_Meta/meta_two_class_great_metanet_lr/weights/backup.pt" #"weights/yolov2_60200.dw" #
    conf_thresh: 0.005
    nms_thresh: 0.45
    reweights: "results/meta_weights/two_class_greater_weights.pkl"
    results: "re_190311_two_class_greater"

weights:
    dataset: 'two_class_base' # "test"
    stdout: True
    gpus: "2"
    nworkers: 4
    pin_mem: True

    input_shape: [416, 416]
    batch_size: 1
    weights: "outputs/Yolov2_Meta/meta_two_class_great_metanet_lr/weights/backup.pt" #"weights/yolov2_60200.dw" #

    results: "results/meta_weights/two_class_greater_weights.pkl"

speed:
    gpus: "7"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]
