output_root: "outputs"
output_version: "hpc"
backup_name: "weights"
log_name: "logs"
model_name: "Yolov2_Meta"
# all labels
labels: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]

# base labels
#labels:  ['aeroplane', 'bicycle', 'boat', 'bottle', 'car', 'cat', 'chair', 'diningtable', 'dog', 'horse', 'person', 'pottedplant', 'sheep', 'train', 'tvmonitor']
data_root_dir: "../VOCdevkit/onedet_cache"

train:
    dataset: "k_shot_3_joint" #"k_shot_base" #"k_shot_joint"
    stdout: True
    gpus: "0,1,2,3"
    nworkers: 16
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: False

    warmup_lr: 0.00001
    lr_steps: [500, 1000, 10000,12000]
    lr_rates: [0.00001,0.0001, 0.00001,0.000001]
    max_batches: 90000
    resize_interval: 10

    backup_interval: 200
    backup_steps: [1000, 60000]
    backup_rates: [1000, 1000]

    input_shape: [416, 416]
    meta_input_shape: [416, 416]
    batch_size: 1
    mini_batch_size: 1
    weights: "weights/darknet19_448.conv.23"

test:
    dataset: 'k_shot_base' #'k_shot_base_test' # "test
    stdout: True
    gpus: "-1"
    nworkers: 16
    pin_mem: True
    input_shape: [416, 416]
    batch_size: 32
    weights: "weights/weights_60000.pt"
    conf_thresh: 0.005
    nms_thresh: 0.45
    reweights: "weights/tmp_60000.pkl"
    results: "reweight_60k_bs32_0512"

weights:
    dataset: "k_shot_base" #'two_class_base' # "test"
    stdout: True
    gpus: "-1"
    nworkers: 1
    pin_mem: True

    input_shape: [416, 416]
    batch_size: 1
    weights: "weights/meta_weights_60000.pt"
    results: "weights/tmp_60000.pkl"
speed:
    gpus: "7"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]
