output_root: "outputs"
output_version: "meta_base"
backup_name: "weights"
log_name: "logs"
model_name: "Yolov2_Meta"
# all labels
#labels: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]

# base labels
labels: ['aeroplane', 'bicycle', 'boat', 'bottle', 'car', 'cat', 'chair', 'diningtable', 'dog', 'horse', 'person', 'pottedplant', 'sheep', 'train', 'tvmonitor']
data_root_dir: "./VOCdevkit/onedet_cache"

train:
    dataset: "k_shot_base" #"k_shot_joint"
    stdout: False
    gpus: "0"
    nworkers: 16
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: False

    warmup_lr: 0.0001
    lr_steps: [400,700,900,1000, 20000]
    lr_rates: [0.0001,0.0005,0.0005,0.001, 0.0001]
    max_batches: 25000
    resize_interval: 10

    backup_interval: 200
    backup_steps: [1000, 60000]
    backup_rates: [1000, 200]

    input_shape: [608, 608]
    batch_size: 4
    mini_batch_size: 1
    weights: "weights/darknet19_448.conv.23"

test:
    dataset: 'k_shot_base_test' # "test"
    stdout: True
    gpus: "1"
    nworkers: 4
    pin_mem: True

    input_shape: [544, 544]
    batch_size: 1
    weights: "outputs/Yolov2_Meta/meta_base/weights/final.dw" #"weights/yolov2_60200.dw" #
    conf_thresh: 0.005
    nms_thresh: 0.45
    reweights: "results/meta_weights/weights.pkl"
    results: "re_190305_base_class"

weights:
    dataset: 'k_shot_base' # "test"
    stdout: True
    gpus: "1"
    nworkers: 4
    pin_mem: True

    input_shape: [608, 608]
    batch_size: 1
    weights: "outputs/Yolov2_Meta/meta_base/weights/backup.pt" #"weights/yolov2_60200.dw" #

    results: "results/meta_weights"

speed:
    gpus: "7"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]
