output_root: "outputs"
output_version: "meta_tiny"
backup_name: "weights"
log_name: "logs"

# all labels
labels: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]

# base labels
#labels:  ['aeroplane', 'bicycle', 'boat', 'bottle', 'car', 'cat', 'chair', 'diningtable', 'dog', 'horse', 'person', 'pottedplant', 'sheep', 'train', 'tvmonitor']
data_root_dir: "../VOCdevkit/onedet_cache"

train:
    dataset: "k_shot_3_joint" #"k_shot_base" #"k_shot_joint"
    stdout: True
    gpus: "2,3,0,1"
    nworkers: 16
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: False

    warmup_lr: 0.0001
    lr_steps: [400,700,900,1000, 40000,60000]
    lr_rates: [0.0005,0.001,0.002,0.02, 0.002,0.0002]
    max_batches: 80200
    resize_interval: 10

    backup_interval: 200
    backup_steps: [1000, 60000]
    backup_rates: [2000, 2000]

    input_shape: [608, 608]
    meta_input_shape: [416, 416]
    batch_size: 32
    mini_batch_size: 8
    weights: ~

test:
    dataset: 'test' #'k_shot_base_test' # "test
    stdout: True
    gpus: "3"
    nworkers: 16
    pin_mem: True


    input_shape: [544, 544]
    batch_size: 32
    weights: "outputs/Yolov2_Meta/great_metanet_lr/weights/backup.pt" #"weights/yolov2_60200.dw" #
    conf_thresh: 0.005
    nms_thresh: 0.45
    reweights: "results/meta_weights/great_metanet_lr.pkl"
    results: "re_190317_great_metanet_lr"

weights:
    dataset: "k_shot_3_joint" #'two_class_base' # "test"
    stdout: True
    gpus: "3"
    nworkers: 4
    pin_mem: True

    input_shape: [416, 416]
    batch_size: 1
    weights: "outputs/Yolov2_Meta/great_metanet_lr/weights/backup.pt" #"weights/yolov2_60200.dw" #
    results: "results/meta_weights/great_metanet_lr.pkl"
speed:
    gpus: "7"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]
