output_root: "outputs"
output_version: "ft"
backup_name: "weights"
log_name: "logs"
model_name: "Yolov2"
labels: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]

data_root_dir: "VOCdevkit/onedet_cache"

train:
    dataset: "k_shot_3_allclass"
    stdout: False
    gpus: "3"
    nworkers: 1
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: True

    warmup_lr: 0.001
    lr_steps: []#[400,700,900,1000, 40000,60000] 
    lr_rates: []#[0.0001,0.0005,0.0005,0.001, 0.0001,0.00001] 
    max_batches: 10000
    resize_interval: 10

    backup_interval: 100
    backup_steps: []
    backup_rates: []

    input_shape: [608, 608]
    batch_size: 8
    mini_batch_size: 8
    weights: "outputs/Yolov2/joint/weights/weights_50000.pt"

test:
    dataset: "test"
    stdout: True
    gpus: "2"
    nworkers: 4
    pin_mem: True

    input_shape: [416, 416]
    batch_size: 16
    weights: "outputs/Yolov2/ft/weights/final.dw"
    conf_thresh: 0.005
    nms_thresh: 0.45

    results: "re_190201_ft_40000"

speed:
    gpus: "7"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]
