output_root: "outputs"
output_version: "exp_0322_joint"
backup_name: "weights"
log_name: "logs"

labels: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]

data_root_dir: "../VOCdevkit/onedet_cache"

train:
    dataset: "k_shot_3_joint" #"k_shot_joint"
    stdout: False
    gpus: "3"
    nworkers: 16
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: False

    warmup_lr: 0.0001
    lr_steps: [400,700,1000, 10000]
    lr_rates: [0.00001,0.00005,0.0001, 0.00001]
    max_batches: 20000
    resize_interval: 10

    backup_interval: 200
    backup_steps: [1000, 60000]
    backup_rates: [1000, 200]

    input_shape: [608, 608]
    batch_size: 64
    mini_batch_size: 16
    weights: "weights/darknet19_448.conv.23"

test:
    dataset: "test"
    stdout: True
    gpus: "0"
    nworkers: 16
    pin_mem: True

    input_shape: [544, 544]
    batch_size: 16
    weights: "weights/tmp.pt" #"weights/yolov2_60200.dw" #
    conf_thresh: 0.005
    nms_thresh: 0.45

    results: "re_190322_joint"

speed:
    gpus: "7"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]
