output_root: "outputs"
output_version: "base_class"
backup_name: "weights"
log_name: "logs"
model_name: "Yolov2dist"
labels: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]

data_root_dir: "./VOCdevkit/onedet_cache"

train:
    dataset: "k_shot_base" #"k_shot_joint"
    stdout: False
    gpus: "1"
    nworkers: 16
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: False

    warmup_lr: 0.0001
    lr_steps: [400,700,900,1000, 20000]
    lr_rates: [0.0001,0.0005,0.0005,0.001, 0.0001]
    max_batches: 25000
    resize_interval: 10

    backup_interval: 200
    backup_steps: [1000, 60000]
    backup_rates: [1000, 200]

    input_shape: [608, 608]
    batch_size: 64
    mini_batch_size: 16
    weights: ~

test:
    dataset: "test"
    stdout: True
    gpus: "2"
    nworkers: 4
    pin_mem: True

    input_shape: [544, 544]
    batch_size: 16
    weights: "outputs/Yolov2/base_class/weights/weights_25000.pt" #"weights/yolov2_60200.dw" #
    conf_thresh: 0.005
    nms_thresh: 0.45

    results: "re_190307_dist"

speed:
    gpus: "7"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]
