output_root: "outputs"
output_version: "ft_novel"
backup_name: "weights"
log_name: "logs"
model_name: "Yolov2dist"
labels: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]

data_root_dir: "./VOCdevkit/onedet_cache"

train:
    dataset: "k_shot_3_finetune" #"k_shot_joint"
    stdout: False
    gpus: "3"
    nworkers: 16
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: True

    warmup_lr: 0.0005
    lr_steps: []
    lr_rates: []
    max_batches: 30000
    resize_interval: 10

    backup_interval: 200
    backup_steps: [1000, 60000]
    backup_rates: [1000, 200]

    input_shape: [608, 608]
    batch_size: 8
    mini_batch_size: 8
    weights: "outputs/Yolov2dist/base_class/weights/weights_60000.pt"

test:
    dataset: "test"
    stdout: True
    gpus: "0"
    nworkers: 4
    pin_mem: True
    reweights: ~
    input_shape: [544, 544]
    batch_size: 16
    weights: "outputs/Yolov2dist/ft_novel/weights/weights_30000.pt" #
    conf_thresh: 0.005
    nms_thresh: 0.45

    results: "re_190310_dist_ftnovel_30000"

speed:
    gpus: "7"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]
